# Generated by Django 4.1.3 on 2022-11-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendaData",
            fields=[
                ("cd_no", models.AutoField(primary_key=True, serialize=False)),
                ("cd_sgi", models.IntegerField()),
                ("cd_sy", models.IntegerField()),
                ("cd_sm", models.TextField()),
                ("cd_sd", models.TextField()),
                ("cd_ly", models.IntegerField()),
                ("cd_lm", models.TextField()),
                ("cd_ld", models.TextField()),
                ("cd_hyganjee", models.TextField(blank=True, null=True)),
                ("cd_kyganjee", models.TextField(blank=True, null=True)),
                ("cd_hmganjee", models.TextField(blank=True, null=True)),
                ("cd_kmganjee", models.TextField(blank=True, null=True)),
                ("cd_hdganjee", models.TextField(blank=True, null=True)),
                ("cd_kdganjee", models.TextField(blank=True, null=True)),
                ("cd_hweek", models.TextField(blank=True, null=True)),
                ("cd_kweek", models.TextField(blank=True, null=True)),
                ("cd_stars", models.TextField(blank=True, null=True)),
                ("cd_moon_state", models.TextField(blank=True, null=True)),
                ("cd_moon_time", models.TextField(blank=True, null=True)),
                ("cd_leap_month", models.IntegerField(blank=True, null=True)),
                ("cd_month_size", models.IntegerField(blank=True, null=True)),
                ("cd_hterms", models.TextField(blank=True, null=True)),
                ("cd_kterms", models.TextField(blank=True, null=True)),
                ("cd_terms_time", models.TextField(blank=True, null=True)),
                ("cd_keventday", models.TextField(blank=True, null=True)),
                ("cd_ddi", models.TextField()),
                ("cd_sol_plan", models.TextField(blank=True, null=True)),
                ("cd_lun_plan", models.TextField(blank=True, null=True)),
                ("holiday", models.IntegerField()),
            ],
            options={"db_table": "calenda_data", "managed": False,},
        ),
    ]
