# Generated by Django 4.1.3 on 2022-11-10 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_manseryuk_year"),
    ]

    operations = [
        migrations.DeleteModel(name="Manseryuk",),
    ]
