# Generated by Django 4.1.3 on 2022-12-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Submits", new_name="Submit",),
    ]
