# Generated by Django 4.1.3 on 2022-12-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_submit_adress_submit_avoid_name_submit_first_name_ch_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submit",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
