# Generated by Django 4.1.3 on 2022-12-07 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_submit_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
