# Generated by Django 4.1.3 on 2022-12-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_alter_person_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person", name="year", field=models.IntegerField(default=2022),
        ),
    ]
