# Generated by Django 4.1.3 on 2022-12-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_alter_person_year"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person", name="gen", field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name="person", name="sl", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="person",
            name="time",
            field=models.CharField(
                choices=[
                    ("자", "子시 23:30~01:30"),
                    ("축", "丑시 01:30~03:30"),
                    ("인", "寅시 03:30~05:30"),
                    ("묘", "卯시 05:30~07:30"),
                    ("진", "辰시 07:30~09:30"),
                    ("사", "巳시 09:30~11:30"),
                    ("오", "午시 11:30~13:30"),
                    ("미", "未시 13:30~15:30"),
                    ("신", "申시 15:30~17:30"),
                    ("유", "酉시 17:30~19:30"),
                    ("술", "戌시 19:30~21:30"),
                    ("해", "亥시 21:30~23:30"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="person", name="year", field=models.IntegerField(),
        ),
    ]
