# Generated by Django 4.1.3 on 2022-12-12 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_alter_person_sl_alter_person_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submit",
            name="category",
            field=models.CharField(
                choices=[
                    ("신생아작명", "신생아작명"),
                    ("개명", "개명"),
                    ("사주상담", "사주상담"),
                    ("궁합", "궁합"),
                    ("택일", "택일"),
                ],
                max_length=20,
            ),
        ),
    ]
