# Generated by Django 4.1.3 on 2022-12-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_alter_submit_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person", name="day", field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="person", name="month", field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name="person", name="year", field=models.CharField(max_length=4),
        ),
    ]
