# Generated by Django 4.1.3 on 2022-11-10 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("manseryuk", "0002_alter_manseryuk_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="manseryuk",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
