# Generated by Django 4.1.3 on 2022-11-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manseryuk", "0003_manseryuk_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cd_no", models.PositiveIntegerField()),
                ("cd_sgi", models.PositiveIntegerField()),
                ("cd_sy", models.PositiveIntegerField()),
                ("cd_sm", models.PositiveIntegerField()),
                ("cd_sd", models.PositiveIntegerField()),
                ("cd_ly", models.PositiveIntegerField()),
                ("cd_lm", models.PositiveIntegerField()),
                ("cd_ld", models.PositiveIntegerField()),
                ("cd_hyganjee", models.CharField(max_length=2)),
                ("cd_kyganjee", models.CharField(max_length=2)),
                ("cd_hmganjee", models.CharField(max_length=2)),
                ("cd_kmganjee", models.CharField(max_length=2)),
                ("cd_hdganjee", models.CharField(max_length=2)),
                ("cd_kdganjee", models.CharField(max_length=2)),
                ("cd_hweek", models.CharField(max_length=1)),
                ("cd_kweek", models.CharField(max_length=1)),
                ("cd_stars", models.CharField(max_length=1)),
                (
                    "cd_moon_state",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "cd_moon_time",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("cd_leap_month", models.IntegerField()),
                ("cd_month_size", models.IntegerField()),
                ("cd_hterms", models.CharField(blank=True, max_length=4, null=True)),
                ("cd_kterms", models.CharField(blank=True, max_length=4, null=True)),
                (
                    "cd_terms_time",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "cd_keventday",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                ("cd_ddi", models.CharField(max_length=2)),
                ("cd_sol_plan", models.CharField(blank=True, max_length=12, null=True)),
                ("cd_lun_plan", models.CharField(blank=True, max_length=12, null=True)),
                ("holiday", models.IntegerField()),
            ],
        ),
    ]
