# Generated by Django 4.1.3 on 2022-11-10 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manseryuk", "0004_calendar"),
    ]

    operations = [
        migrations.RemoveField(model_name="calendar", name="cd_no",),
    ]
