# Generated by Django 4.1.3 on 2022-11-10 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manseryuk", "0005_remove_calendar_cd_no"),
    ]

    operations = [
        migrations.DeleteModel(name="Calendar",),
    ]
